### PR TITLE
SCHED-168 and SCHED-226: ResourceMock rewrite and lookup tables for FPU barcodes

### PR DESCRIPTION
**Pull request by sraaphorst**
Not quite ready for merge, but request for comments.
Added back data files.

### CODE REVIEW

**Review by stroncod — APPROVED** [review]

**Comment by sraaphorst** [comment]
The error should be fixed now, but I want to move some things to `OcsProgramProvider.`

**Review by stroncod — APPROVED** [review]
I'm confused on the addition of Site in some methods but looks good.

**Comment by sraaphorst** [comment]
The site was added because we're using barcodes as the `Resource` IDs, and we want to differentiate between sites since some of the barcodes might overlap.

**Comment by sraaphorst** [comment]
For example, `IFU-R` has barcodes 1000009 or something like that at both sites, but might not be active at both sites.

**Pull request merged**
